<?

include '../lib/auth.php';
include '../lib/keygen.php';

$passed_item = $_GET['item'];
$passed_likes = $_GET['likes'];

if (empty($passed_likes)) $passed_likes = 1;
else $passed_likes = intval($passed_likes);

if ($authuser_type == "admin" && $session_ip == "82.23.4.163") {	
	if (empty($passed_item)) {
		$json_status = 'item parameter missing';
		$json_output[] = array('status' => $json_status, 'error_code' => '301');
		echo json_encode($json_output);
		exit;
		
	}
	else {
		$exists_query = mysqli_query("");
		$exists_count = mysql_num_rows($exists_query);
		
		for ($k = 0; $k < $passed_likes; $k++) {
			$like_user = "user_TEST" . generate_key();
			$like_key = "like_" . generate_key();
			$like_post = mysqli_query("INSERT INTO `likes` (`like_id`, `like_key`, `like_timestamp`, `like_user`, `like_content`, `like_latitude`, `like_longitude`) VALUES (NULL, '$like_key', CURRENT_TIMESTAMP, '$like_user', '$passed_item', '0', '0');");
			if ($like_post) {
				$likes_added ++;
				$like_output[] = array("key" => $like_key, "user" => $like_user);
				
			}
			
		}
		
		$json_status = 'autogenerated ' . $likes_added . ' new like ' . $passed_likes;
		$json_output[] = array('status' => $json_status, 'error_code' => '200', 'output' => $like_output);
		echo json_encode($json_output);
		exit;
		
	}
}
else {
	$json_status = 'user does not have the privileges to access this api';
	$json_output[] = array('status' => $json_status, 'error_code' => '349');
	echo json_encode($json_output);
	exit;
	
}

?>
	